package com.sharcg.compare.bean;

import java.math.BigDecimal;
import java.util.Date;

public class PafAcctAmtMatchDO {
    private Long id;

    private String batchNo;

    private Long fileSummaryId;

    private String fundCodePafAssetAcct;

    private String bizCode;

    private String prodCode;

    private String custId;

    private String incomeDate;

    private String pafAssetAcct;

    private BigDecimal pafTotalAmt;

    private String matchFlag;

    private Date createTime;

    private Date modifyTime;
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.ID
     *
     * @param id the value for T_FTS_PAF_ACCT_AMT_MATCH.ID
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.BATCH_NO
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.BATCH_NO
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.BATCH_NO
     *
     * @param batchNo the value for T_FTS_PAF_ACCT_AMT_MATCH.BATCH_NO
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.FILE_SUMMARY_ID
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.FILE_SUMMARY_ID
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public Long getFileSummaryId() {
        return fileSummaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.FILE_SUMMARY_ID
     *
     * @param fileSummaryId the value for T_FTS_PAF_ACCT_AMT_MATCH.FILE_SUMMARY_ID
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setFileSummaryId(Long fileSummaryId) {
        this.fileSummaryId = fileSummaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.FUND_CODE_PAF_ASSET_ACCT
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.FUND_CODE_PAF_ASSET_ACCT
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getFundCodePafAssetAcct() {
        return fundCodePafAssetAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.FUND_CODE_PAF_ASSET_ACCT
     *
     * @param fundCodePafAssetAcct the value for T_FTS_PAF_ACCT_AMT_MATCH.FUND_CODE_PAF_ASSET_ACCT
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setFundCodePafAssetAcct(String fundCodePafAssetAcct) {
        this.fundCodePafAssetAcct = fundCodePafAssetAcct == null ? null : fundCodePafAssetAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.BIZ_CODE
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.BIZ_CODE
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.BIZ_CODE
     *
     * @param bizCode the value for T_FTS_PAF_ACCT_AMT_MATCH.BIZ_CODE
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.PROD_CODE
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.PROD_CODE
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getProdCode() {
        return prodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.PROD_CODE
     *
     * @param prodCode the value for T_FTS_PAF_ACCT_AMT_MATCH.PROD_CODE
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setProdCode(String prodCode) {
        this.prodCode = prodCode == null ? null : prodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.CUST_ID
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.CUST_ID
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.CUST_ID
     *
     * @param custId the value for T_FTS_PAF_ACCT_AMT_MATCH.CUST_ID
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.INCOME_DATE
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.INCOME_DATE
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.INCOME_DATE
     *
     * @param incomeDate the value for T_FTS_PAF_ACCT_AMT_MATCH.INCOME_DATE
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setIncomeDate(String incomeDate) {
        this.incomeDate = incomeDate == null ? null : incomeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.PAF_ASSET_ACCT
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.PAF_ASSET_ACCT
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getPafAssetAcct() {
        return pafAssetAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.PAF_ASSET_ACCT
     *
     * @param pafAssetAcct the value for T_FTS_PAF_ACCT_AMT_MATCH.PAF_ASSET_ACCT
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setPafAssetAcct(String pafAssetAcct) {
        this.pafAssetAcct = pafAssetAcct == null ? null : pafAssetAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.PAF_TOTAL_AMT
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.PAF_TOTAL_AMT
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public BigDecimal getPafTotalAmt() {
        return pafTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.PAF_TOTAL_AMT
     *
     * @param pafTotalAmt the value for T_FTS_PAF_ACCT_AMT_MATCH.PAF_TOTAL_AMT
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setPafTotalAmt(BigDecimal pafTotalAmt) {
        this.pafTotalAmt = pafTotalAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.MATCH_FLAG
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.MATCH_FLAG
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public String getMatchFlag() {
        return matchFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.MATCH_FLAG
     *
     * @param matchFlag the value for T_FTS_PAF_ACCT_AMT_MATCH.MATCH_FLAG
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setMatchFlag(String matchFlag) {
        this.matchFlag = matchFlag == null ? null : matchFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.CREATE_TIME
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.CREATE_TIME
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.CREATE_TIME
     *
     * @param createTime the value for T_FTS_PAF_ACCT_AMT_MATCH.CREATE_TIME
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.MODIFY_TIME
     *
     * @return the value of T_FTS_PAF_ACCT_AMT_MATCH.MODIFY_TIME
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_FTS_PAF_ACCT_AMT_MATCH.MODIFY_TIME
     *
     * @param modifyTime the value for T_FTS_PAF_ACCT_AMT_MATCH.MODIFY_TIME
     *
     * @mbggenerated Thu Nov 12 14:29:31 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}